version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # Dependabot automatically detects pnpm from pnpm-lock.yaml
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@warp-drive/*"
    versioning-strategy: increase
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # This configuration allows Dependabot to update @warp-drive/* packages to canary/pre-release versions
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@ember-data/*"
    versioning-strategy: increase
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # This configuration allows Dependabot to update @ember-data/* packages to canary/pre-release versions
